### ISSUE TITLE
Missing slayer boost

### ISSUE THREAD

**Issue by Troelsbr** [XrioBtw/effectivelevel-plugin#3]
Would be amazing to add the slayer boost option aswell!

**Comment by Troelsbr** [comment]
Alternatively add the 16,67% melee / 15% ranged magic multiplier when slayer helm is equiped

**Comment by XrioBtw** [comment]
Slayer helm, black mask and salve amulet boosts are not part of the effective level. These boosts are however applied to the max hit, which is not part of this plugin. For more info on the order of applied boosts [see section 3 on page 3 and 4 of this combat formula document](https://docs.google.com/document/d/1hk7FxOAOFT4oxguC8411QQhE4kk-_GzqWcwkaPmaYns/edit) or [the wiki page on the same topic](https://oldschool.runescape.wiki/w/Maximum_melee_hit).

Although the following is not what the game is doing, it would be theoretically possible to display the number of strength/ranged levels needed to compensate for using a slayer helm. This however would require a substantial rewrite of this plugin to include max hit calculation, and would still be inaccurate due to inability to reliably know e.g. the current slayer task monster and opponent [monster attributes](https://oldschool.runescape.wiki/w/Monster_attribute).
